# Общие терапевтические шаблоны
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":reci"
    replace: "Рекомендовано соблюдение рекомендаций лечащего врача и врачей-консультантов. "

  - trigger: ".план"
    replace: "План обследования: ОАК, ОАМ, БХ, ЭКГ."

  - trigger: ":cons"
    replace: "Консультации врачей-специалистов:"

  - trigger: ":pocr"
    replace: "Лечение назначено в соответствии с клиническими рекомендациями Министерства Здравоохранения Российской Федерации. "

  - trigger: ":pocr"
    replace: "Диагноз установлен на основании жалоб пациента, анамнеза, лабораторно-инструментальных данных, данных из электронно-медицинской карты и консультаций врачей-специалистов."

  - trigger: ":smotr"
    replace: "Осмотр врача-терапевта на приеме. Врач-терапевт: Куцин И.Ю."

  - trigger: ":smotr"
    replace: "Осмотр врача-терапевта на дому. Врач-терапевт: Куцин И.Ю."

  - trigger: ":hospital"
    replace: "На момент осмотра терапевтических противопоказаний к плановой госпитализации и оперативному вмешательству нет."

  - trigger: ".отм"
    replace: "На момент осмотра от {{current_date}}: "
    vars:
      - name: current_date
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: ".сорбифер"
    replace: "Железа сульфат + [аскорбиновая кислота] 320 мг + 60 мг по 1 таблетке на прием 2 раза в сутки во время на 3 месяца, контроль ОАК через 2 недели с оценкой ретикулоцитоза."

  - trigger: ".вич"
    replace: "Пациент информирован о возможности медицинского освидетельствования для выявления ВИЧ-инфекции с соответствии со статьей 7 Федерального Закона от 30.03.1995г. №38-ФЗ «О предупреждении распространения в Российской Федерации заболевания, вызываемого вирусом иммунодефицита человека (ВИЧ-инфекции).\nДотестовое консультирование на ВИЧ проведено."

  - trigger: ".вич"
    replace: "Послетестовое консультирование по ВИЧ-инфекции проведено, результат отрицательный от "
