/*
 * This file is part of espanso.
 *
 * Copyright (C) 2019-2021 Federico Terzi
 *
 * espanso is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * espanso is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with espanso.  If not, see <https://www.gnu.org/licenses/>.
 */

pub mod clipboard_injector;
pub mod context_menu;
pub mod event_injector;
pub mod icon;
pub mod key_injector;
pub mod secure_input;
pub mod text_ui;

pub trait InjectParamsProvider {
    fn get(&self) -> InjectParams;
}

pub struct InjectParams {
    pub inject_delay: Option<usize>,
    pub key_delay: Option<usize>,
    pub disable_x11_fast_inject: bool,
    pub evdev_modifier_delay: Option<usize>,
    pub x11_use_xdotool_backend: bool,
}

/// Execute one injector operation while the Astra X11 detector ignores
/// keyboard transitions generated by our own XTest calls.
///
/// XQueryKeymap has no provenance bit, so without this guard a synthetic
/// Backspace used to erase the trigger is indistinguishable from a physical
/// Backspace. The undo middleware then restores the trigger immediately,
/// producing artifacts such as `0:date` and disappearing replacement text.
pub fn with_synthetic_input_guard<T>(
    operation: impl FnOnce() -> anyhow::Result<T>,
) -> anyhow::Result<T> {
    if cfg!(all(target_os = "linux", not(feature = "wayland"))) {
        struct Guard;
        impl Drop for Guard {
            fn drop(&mut self) {
                // Keep suppression active for several 5 ms detector polls so
                // delayed XTest press/release transitions are drained too.
                std::thread::sleep(std::time::Duration::from_millis(30));
                espanso_detect::end_synthetic_input_suppression();
            }
        }

        espanso_detect::begin_synthetic_input_suppression();
        let _guard = Guard;
        operation()
    } else {
        operation()
    }
}
